// packages/angular/src/app/button/button.component.ts
import { Component, Input } from '@angular/core';
import * as tokens from '../../../../tokens/tokens.json';

@Component({
  selector: 'app-button',
  templateUrl: './button.component.html',
  styleUrls: ['./button.component.css']
})
export class ButtonComponent {
  @Input() label: string = '';
  @Input() variant: 'primary' | 'secondary' = 'primary';

  getStyle() {
    return {
      'background-color': tokens.color[this.variant].value,
      'color': '#fff',
      'padding': `${tokens.space.medium.value} ${tokens.space.large.value}`,
      'border': 'none',
      'border-radius': '4px',
      'cursor': 'pointer',
      'font-family': tokens.typography.fontFamily.value,
      'font-size': tokens.typography.fontSize.medium.value,
      'font-weight': tokens.typography.fontWeight.bold.value,
    };
  }
}

<button [ngStyle]="getStyle()">{{ label }}</button>

// packages/react/src/Button.tsx
import React from 'react';
import tokens from '../../tokens/tokens.json';

interface ButtonProps {
  label: string;
  variant: 'primary' | 'secondary';
  onClick?: () => void;
}

const Button: React.FC<ButtonProps> = ({ label, variant, onClick }) => {
  const buttonStyle = {
    backgroundColor: tokens.color[variant].value,
    color: '#fff',
    padding: `${tokens.space.medium.value} ${tokens.space.large.value}`,
    border: 'none',
    borderRadius: '4px',
    cursor: 'pointer',
    fontFamily: tokens.typography.fontFamily.value,
    fontSize: tokens.typography.fontSize.medium.value,
    fontWeight: tokens.typography.fontWeight.bold.value,
  };

  return (
    <button style={buttonStyle} onClick={onClick}>
      {label}
    </button>
  );
};

export default Button;
